### ISSUE TITLE
Does not work for dedicated servers (2.0.2)

### ISSUE THREAD

**Issue by C-o-l-l-i-n** [LiskoSlayer63/garbagebins#2]
Failure message: Garbage Bins (garbagebins) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
        Mod Version: 2.0.2

**Comment by LiskoSlayer63** [comment]
This should be fixed in version 2.0.3
